[package]
name = "open-stock"
version = "0.1.4"
edition = "2021"
authors = ["bennjii"]
license = "MIT"
description = "An Inventory Management Database Interface Layer for MySQL"

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
dotenv = "0.15.0"
async-std = { version = "^1.9", features = [ "attributes", "tokio1" ] }
uuid = { version = "1.2.2", features = [ "v4", "fast-rng", "serde" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sea-orm-rocket = { version = "0.5.2" }
sea-orm = { version = "^0.10.3", features = [
  "macros",
  "runtime-tokio-native-tls",
  "sqlx-mysql"
]}
futures = { version = "^0.3" }
async-stream = { version = "^0.3" }
futures-util = { version = "^0.3" }
async-trait = { version = "0.1.58" }
rocket = { version = "0.5.0-rc.2", features = [
  "json", "secrets", "tls"
] }
rust-argon2 = "1.0"
# argon2rs = { version = "0.2.5", features = ["simd"] }
# argonautica = { version = "0.2", features = ["simd"] }
futures-cpupool = "0.1.8"
rand = "0.8.5"
photon-geocoding = { version = "1.1.0" }
geo = "0.23.1"
tokio = "1.22.0"
# rocket_contrib = "0.4.11"
alea = "0.2"

[dev-dependencies]
tokio = { version = "1.22.0", features = ["rt"] }
reqwest = "0.11.13"

[features]
default = ["sqlx-postgres", "sqlx-sqlite"]
sqlx-mysql = ["sea-orm/sqlx-mysql"]
sqlx-postgres = ["sea-orm/sqlx-postgres"]
sqlx-sqlite = ["sea-orm/sqlx-sqlite"]