[package]
name = "open-stock"
version = "0.1.14"
edition = "2021"
authors = ["bennjii"]
license = "MIT"
description = "An Inventory Management Database Interface Layer for MySQL"

[dependencies]
sea-orm = { version = "0.12.1", features = [
  "macros",
  "runtime-tokio-native-tls",
  "sqlx-mysql"
], optional = true}
tokio = { version = "1.28.2", features = ["rt"], optional = true }
rocket = { version = "0.5.0-rc.3", features = [
  "json", "secrets", "tls"
], optional = true }
sea-orm-rocket = { version = "0.5.2", optional = true }
async-std = { version = "^1.9", features = [ "attributes", "std" ], optional = true }

sea-orm-migration = "0.12.1"
chrono = { version = "0.4.23", features = ["serde"] }
dotenv = "0.15.0"
uuid = { version = "1.2.2", features = [ "v4", "fast-rng", "serde" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-argon2 = "1.0"
futures-cpupool = "0.1.8"
rand = "0.8.5"
photon-geocoding = { version = "1.1.0" }
geo = "0.23.1"
alea = "0.2"
regex = "1.5.4"
lazy_static = "1.4.0"
futures = { version = "^0.3" }
async-stream = { version = "^0.3" }
futures-util = { version = "^0.3" }
async-trait = { version = "0.1.58" }

[dev-dependencies]
reqwest = "0.11.13"

[features]
types = []
process = ["sea-orm", "tokio", "rocket", "sea-orm-rocket", "async-std"]
methods = ["types"]
sql = ["methods"]
all = ["types", "methods", "sql", "process", "sea-orm/sqlx-mysql"]
default = ["types"]

[profile.release]
strip = false
