[package]
name = "open-stock"
version = "0.1.8"
edition = "2021"
authors = ["bennjii"]
license = "MIT"
description = "An Inventory Management Database Interface Layer for MySQL"

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
dotenv = "0.15.0"
async-std = { version = "^1.9", features = [ "attributes", "tokio1" ] }
uuid = { version = "1.2.2", features = [ "v4", "fast-rng", "serde" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sea-orm-rocket = { version = "0.5.2" }
sea-orm = { version = "0.12.1", features = [
  "macros",
  "runtime-tokio-native-tls",
  "sqlx-mysql"
]}
sea-orm-migration = "*"
futures = { version = "^0.3" }
async-stream = { version = "^0.3" }
futures-util = { version = "^0.3" }
async-trait = { version = "0.1.58" }
rocket = { version = "0.5.0-rc.3", features = [
  "json", "secrets", "tls"
] }
rust-argon2 = "1.0"
futures-cpupool = "0.1.8"
rand = "0.8.5"
photon-geocoding = { version = "1.1.0" }
geo = "0.23.1"
tokio = "1.22.0"
alea = "0.2"
regex = "1.5.4"
lazy_static = "1.4.0"

[dev-dependencies]
tokio = { version = "1.22.0", features = ["rt"] }
reqwest = "0.11.13"

[features]
types = []
process = []
methods = ["types"]
sql = ["methods"]
default = ["types", "methods", "sql", "process", "sea-orm/sqlx-mysql"]

[profile.release]
strip = false
