[package]
name = "stock"
version = "0.1.0"
edition = "2018"
authors = ["unrealg@UnRealReincarlution"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies.redis]
version = "*"

[dependencies.chrono]
version = "*"

[dependencies.serde]
version = "*"
features = ["derive"]

[dependencies.serde_json]
version = "*"

[dependencies.termcolor]
version = "1.1"