# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  open-stock:
    image: ghcr.io/bennjii/open-stock:latest
    platform: "linux/amd64"
    restart: always
    ports: 
      - "8000:8000"
    links:
      - "db:database"
    environment:
      - DATABASE_URL=mysql://root:root@database/stock
      - ROCKET_SECRET_KEY=e5c63abf90fb076d7037a32d8dc2951c4b402e7357ca84b0da8e03595f84b30f
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000

  open-pos:
    platform: "linux/amd64"
    image: ghcr.io/bennjii/open-pos:latest
    restart: always
    ports: 
      - "80:3000"