[development]
address = "0.0.0.0"
log = "normal"

[staging]
address = "0.0.0.0"
log = "normal"

[production]
address = "0.0.0.0"
log = "critical"

[release]
address = "0.0.0.0"
log = "critical"

[global.limits]
file = 1073741824 # 1 GiBs
forms = 1073741824 # 1 GiB

[global]
address = "0.0.0.0"
ident = "openstock"
port = 8080