name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  release:
    types: [ published ]

jobs:
  build-amd:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
        - uses: actions/checkout@v3
        - uses: docker/setup-buildx-action@v2
        - name: Login to GCR
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v1
          with:
              registry: australia-southeast1-docker.pkg.dev
              username: _json_key
              password: ${{ secrets.GAR_JSON_KEY }}
        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            platforms: linux/amd64
            push: true
            tags: open-stock:latest

  build-arm:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    steps:
        - uses: actions/checkout@v3
        - uses: docker/setup-buildx-action@v2
        - name: Login to GCR
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v1
          with:
              registry: australia-southeast1-docker.pkg.dev
              username: _json_key
              password: ${{ secrets.GAR_JSON_KEY }}
        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            platforms: linux/arm64
            push: true
            tags: open-stock:latest-arm
